Podfile
Podfile.lock
Prox/Prox.xcodeproj/project.pbxproj
Prox/Prox/FirebasePlacesDatabase.swift
Prox/Prox/Models/Place.swift
Prox/Prox/Models/ReviewProvider.swift
Prox/Prox/PlaceCarousel/PlaceCarousel.swift
Prox/Prox/PlaceCarouselViewController.swift
Prox/Prox/PlacesDatabase.swift

There are many TODOs and it's not very robust but this may allow us to better break up the remaining work to do.
@fluffyemily, if you don't feel we should merge this yet, let me know.

Query the database and insert results into the UI

---

Prox/Prox/Models/Place.swift
Prox/Prox/PlaceCarousel/PlaceCarousel.swift

The image downloader will need to be moved in order for the place details card
to access it (to use the same cache).
That being said this is a first run to get something in so that we have
something to move forward with when designing the place details.
(May merge conflict with my places label PR – github makes it hard to build a branch on top of another one and keep the reviews clean 😢)

Download and insert place carousel images.

---

Prox/Prox.xcodeproj/project.pbxproj
Prox/Prox/Models/Place.swift
Prox/Prox/Models/ReviewProvider.swift
Prox/Prox/PlaceDetails/PlaceDetailsCardView.swift
Prox/Prox/PlaceDetails/PlaceDetailsCardViewController.swift
Prox/ProxTests/DayOfWeekTests.swift
Prox/ProxTests/OpenHoursTests.swift

Not quite done but we could merge this if you'd like.

Add (some) place details with live data

---

Prox/Prox/PlaceCarousel/PlaceCarousel.swift
Prox/Prox/Utilities/PlaceUtilities.swift

Closes #128: Shorten "No data" text on map view.

---

Prox/Prox/PlaceDetails/PlaceDetailsCardView.swift
Prox/Prox/PlaceDetails/PlaceDetailsIconInfoView.swift

Closes #85: Match updated mocks for "You're Here" UI.

---

Prox/Prox.xcodeproj/project.pbxproj
Prox/Prox/Data/EventsController.swift
Prox/Prox/Data/EventsDatabase.swift
Prox/Prox/Data/FakeEventsDatabase.swift
Prox/Prox/Data/FirebaseEventsDatabase.swift
Prox/Prox/Data/PlacesController.swift
Prox/Prox/Models/Event.swift
Prox/Prox/PlaceCarousel/PlaceCarouselViewController.swift
Prox/Prox/RemoteConfigDefaults.plist
Prox/Prox/RemoteConfigKeys.swift
Prox/Prox/Utilities/AppConstants.swift
Prox/Prox/Utilities/EventNotificationsManager.swift

Following the architecture started by @mcomella

Issue #192 fetch events from firebase

---

Prox/Prox.xcodeproj/project.pbxproj
Prox/Prox/Extensions/TimeInterval.swift
Prox/Prox/Models/Event.swift
Prox/Prox/Models/Place.swift
Prox/Prox/PlaceDetails/PlaceDetailsCardView.swift
Prox/Prox/PlaceDetails/PlaceDetailsCardViewController.swift
Prox/Prox/PlaceDetails/PlaceDetailsEventView.swift
Prox/Prox/RemoteConfigDefaults.plist
Prox/Prox/RemoteConfigKeys.swift

Detect when places have events and display their details
Put notifications / place details banner text into remote config so it can be tweaked without any need to redeploy the app

Issue 194 wire events to place details

---

Prox/Prox.xcodeproj/project.pbxproj
Prox/Prox/AppDelegate.swift
Prox/Prox/Data/EventsController.swift
Prox/Prox/PlaceCarousel/PlaceCarouselViewController.swift
Prox/Prox/RemoteConfigDefaults.plist
Prox/Prox/RemoteConfigKeys.swift
Prox/Prox/Utilities/EventNotificationsManager.swift
Prox/ProxTests/EventsProviderTests.swift

There is one question open to Bram at the moment. See comment on issue #170

Closes #170  - implement event notification criteria

---

Prox/Prox/PlaceDetails/PlaceDetailViewController.swift
Prox/Prox/PlaceDetails/PlaceDetailsCardViewController.swift

https://github.com/mozilla-mobile/prox/issues/61
* Carousel for places will auto-advance at a speed of 6 seconds
* When carousel is touched in anyway the auto-advance is stopped

Issue 61 - Implemented auto-advance of carousel

---

Prox/Prox.xcodeproj/project.pbxproj
Prox/Prox.xcodeproj/xcshareddata/xcschemes/Prox.xcscheme
Prox/Prox/MapPlacesTransition.swift
Prox/Prox/Models/Place.swift
Prox/Prox/PlaceCarousel/PlaceCarousel.swift
Prox/Prox/PlaceCarousel/PlaceCarouselCollectionViewCell.swift
Prox/Prox/PlaceCarousel/PlaceCarouselViewController.swift
Prox/Prox/PlaceDetails/PlaceDetailViewController.swift
Prox/Prox/PlaceDetails/PlaceDetailsDescriptionView.swift
Prox/Prox/Utilities/Animatable.swift

First pass at creating the custom presenting transition between the map/detail view. I tried to make it as close as I could to the mock up with some exceptions for new things like the map button.

Issue 154 - Added transition animation when going from and to the place detail view

---

Prox/Prox/MapPlacesTransition.swift
Prox/Prox/PlaceDetails/PlaceDetailViewController.swift

Adds an alpha/scaling/translate animation when swiping between cards in the detail view

Issue 233 - Card Fade Fanciness

---

Prox/Prox/PlaceCarousel/PlaceCarouselCollectionViewCell.swift
Prox/Prox/PlaceCarousel/PlaceCarouselViewController.swift

Fixed up place cell shadow and adjusted carousel height to show shadow below cell

Issue 278 - Fixed selected/non-selected shadow on place cells

---

Prox/Prox/PlaceDetails/PlaceDetailViewController.swift

Added a crossfade when setting the background image in the detail view controller whenever the user moves either the cards or the pages.

Issue 60 - Added crossfade animation when setting the background image of the detail view

---

Prox/Prox/PlaceCarousel/PlaceCarouselCollectionViewCell.swift
Prox/Prox/PlaceCarousel/PlaceCarouselViewController.swift

The original change I made to the Issue 278 PR included a self-referential issue when I did the minor cleanup. I've reverted that PR and opened this one so I can merge it using Github.

Issue 278 (#2) - Fix for shadow that doesn't crash master

---

Prox/Prox/Data/FirebasePlacesDatabase.swift
Prox/Prox/Utilities/AppConstants.swift

This should be merged only after the production server is running.
https://github.com/mozilla-mobile/prox/issues/270

Closes #270 – add configuration to point to production servers/firebase.

---

Prox/Prox.xcodeproj/project.pbxproj
Prox/Prox/Extensions/URL.swift
Prox/Prox/PlaceDetails/PlaceDetailsCardViewController.swift
Prox/ProxTests/URLTests.swift

#421 – speculative fix as I didn't have time to test.

#421: make clicking on events without an http scheme specified work better

---

Prox/Prox/Models/Place.swift
Prox/Prox/Models/PlaceProviders.swift
Prox/Prox/PlaceDetails/PlaceDetailsCardViewController.swift
Prox/Prox/Utilities/CategoriesUtil.swift
Prox/Prox/Utilities/PlaceUtilities.swift
Prox/ProxTests/CategoriesUtilTests.swift

I _think_ this should work, but the Firebase DB hasn't been updated to include Yelp v3 yet, so all the places currently have empty categories. This should be ready for review once places start showing up.

Closes #514 - Add Yelp v3 and re-enable photos/categories

---

Prox/Prox/Data/PlacesController.swift
Prox/Prox/Utilities/PlaceUtilities.swift

Eased dependencies between code & added hack to show travel times for initial places.

Closes #584: Show travel times for initial places list.

---

Prox/Prox.xcodeproj/project.pbxproj
Prox/Prox/Extensions/CLLocation.swift
Prox/Prox/Map View/MapViewController.swift
Prox/Prox/Map View/MapViewSearchButton.swift
Prox/Prox/PlaceDetails/PlaceDetailViewController.swift
Prox/Prox/Utilities/Colors.swift
Prox/Prox/Utilities/Fonts.swift
Prox/Prox/Utilities/Strings.swift

#563 
I didn't have enough time to fully finish but I think this is good enough:
1. There is no "reset" button in dialog
1. When the user clicks "Search here", it only finds places in our initial search radius, not a radius calculated for the current zoom level
1. The code is pretty hairy
@antlam I'm most concerned about 2. What do you think?

Closes #563: future planning in map view

---

Prox/Prox.xcodeproj/project.pbxproj
Prox/Prox/PlaceDetails/FilterViewController.swift
Prox/Prox/Utilities/Colors.swift
Prox/Prox/Utilities/Fonts.swift
Prox/Prox/Utilities/Strings.swift
Prox/Prox/Widgets/Toast.swift

Shows a toast the first time the user turns on popularity sort.

Closes #620: Show toast explaining popularity sort

---

Prox/Prox/Map View/MapViewController.swift
Prox/Prox/PlaceDetails/PlaceDetailViewController.swift

Copied from `FilterViewController`, using different views the for animations.

Closes #544: Transition map view controller in from top

---

Prox/Prox/Widgets/Toast.swift

I experienced Exceptions otherwise.

No issue: assert Toast.show is called on main thread.

---

Prox/Prox/Data/PlacesController.swift
Prox/Prox/Map View/MapViewController.swift
Prox/Prox/PlaceDetails/PlaceDetailViewController.swift

No issue: PlacesProvider cleanup

---

Prox/Prox.xcodeproj/project.pbxproj
Prox/Prox/Extensions/SnapKit.swift
Prox/Prox/PlaceDetails/PlaceDetailViewController.swift
Prox/Prox/PlaceDetails/PlaceDetailsCardView.swift
Prox/Prox/Widgets/ExpandingCardView.swift

This simplifies the code by encapsulating the shadow functionality into the
CardView. I think we could further simplify the code by removing the
PlaceDetailsCardDelegate.

No issue: extend ExpandingCardView in PlaceDetailsCardView
